# Runs the cfwheels core tests across engine/db combos in Docker

name: Wheels Test Suite

on:
  push:
    branches: [github-actions-ci]
  pull_request:
    branches: [github-actions-ci]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cf: [lucee5, adobe2016, adobe2018]
        db: [mysql56, postgres, sqlserver]

    steps:
      - uses: actions/checkout@v2

      - name: Install Commandbox
        run: src/github/tests/commandbox.sh

      - name: Docker Compose ${{ matrix.cf }} ${{ matrix.db }}
        run: docker-compose up -d ${{ matrix.cf }} ${{ matrix.db }}

      - name: Wait for ${{ matrix.cf }} startup
        run: src/github/tests/server-up.sh ${{ matrix.cf }}

      - name: Run core tests ${{ matrix.cf }} ${{ matrix.db }}
        run: src/github/tests/core-tests.sh ${{ matrix.cf }} ${{ matrix.db }}
