# Runs the cfwheels core tests across engine/db combos in Docker

name: CI

on:
  push:
    branches: [github-actions-ci]
  pull_request:
    branches: [github-actions-ci]

jobs:
  cfwheels-test-suite-lucee5-mysql:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Compose
        run: docker-compose up -d lucee5 mysql

      - name: Wait for server startup
        run: src/github/tests/server-up.sh 60005

      - name: Run core tests
        run: src/github/tests/core-tests.sh 60005 lucee5 mysql

  cfwheels-test-suite-adobe2016-mysql:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Compose
        run: docker-compose up -d adobe2016 mysql

      - name: Wait for server startup
        run: src/github/tests/server-up.sh 62016

      - name: Run core tests
        run: src/github/tests/core-tests.sh 62016 adobe2016 mysql

  cfwheels-test-suite-adobe2018-mysql:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Compose
        run: docker-compose up -d adobe2018 mysql

      - name: Wait for server startup
        run: src/github/tests/server-up.sh 62018

      - name: Run core tests
        run: src/github/tests/core-tests.sh 62018 adobe2018 mysql

    # TODO: all the combos


      # - name: Wait for ACF 2016 startup
      #   run: src/github/tests/server-up.sh 62016

      # - name: Wait for ACF 2018 startup
      #   run: src/github/tests/server-up.sh 62018

 # - name: Wait for ACF 2016 startup
      #   run: src/github/tests/server-up.sh 62016

      # - name: Wait for ACF 2018 startup
      #   run: src/github/tests/server-up.sh 62018


      # - name: Run lucee5 sqlserver core tests
      #   run: src/github/tests/core-tests.sh 60005 lucee5 sqlserver

      # - name: Run lucee5 postgres core tests
      #   run: src/github/tests/core-tests.sh 60005 lucee5 postgres

      # - name: Run adobe2016 mysql core tests
      #   run: src/github/tests/core-tests.sh 62016 adobe2016 mysql
